# Generated by Django 4.0.3 on 2022-03-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0003_film_imdb_rating_film_opis_film_plakat_film_premiera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Figura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.PositiveSmallIntegerField()),
                ('b', models.PositiveSmallIntegerField()),
                ('c', models.PositiveSmallIntegerField(blank=True)),
                ('rodzaj', models.CharField(max_length=10)),
            ],
        ),
    ]
