# Generated by Django 4.0.3 on 2022-03-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0004_figura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figura',
            name='c',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
