# Generated by Django 4.0.3 on 2022-04-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liczniki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licznik',
            name='licznik_id',
            field=models.SmallIntegerField(),
        ),
    ]
