# Generated by Django 4.0.3 on 2022-03-25 14:58

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_profile_my_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('kuchnia', 'Kuchnia'), ('lazienka', 'Lazienka'), ('salon', 'Salon'), ('jadalnia', 'Jadalnia'), ('sypialnia', 'Sypialnia'), ('ogolne', 'Ogolne')], default='ogolne', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='my_field',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('kuchnia', 'Kuchnia'), ('lazienka', 'Lazienka'), ('salon', 'Salon'), ('jadalnia', 'Jadalnia'), ('sypialnia', 'Sypialnia'), ('ogolne', 'Ogolne')], default='item_key1', max_length=48),
        ),
    ]
