# Generated by Django 4.0.3 on 2022-03-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('Pole Tekstowe', 'Text Field'), ('Pojedynczego wybory', 'Singlechoice'), ('Wielokrotnego wyboru', 'Multiplechoice'), ('Skala', 'Scale')], default='Pole Tekstowe', max_length=30),
        ),
    ]
