# Generated by Django 4.0.3 on 2022-03-24 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
