# Generated by Django 4.0.3 on 2022-04-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_question_question_type_alter_profile_my_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
