# Generated by Django 4.0.3 on 2022-04-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_question_choice_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choice_text',
            field=models.CharField(blank=True, default=' ', max_length=200),
        ),
    ]
